### ISSUE TITLE
Render problem

### ISSUE THREAD

**Issue by robineki** [wdullaer/SwipeActionAdapter#54]
I am stuck on this error/bug and i need help. Adapter still throwing this error:
```bash
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.wdullaer.swipeactionadapter.SwipeViewGroup.showBackground(com.wdullaer.swipeactionadapter.SwipeDirection, boolean)' on a null object reference
                                                                        at com.wdullaer.swipeactionadapter.SwipeActionTouchListener.onTouch(SwipeActionTouchListener.java:419)
                                                                        at android.view.View.dispatchTouchEvent(View.java:9290)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2547)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                        at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                                        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                        at android.app.Activity.dispatchTouchEvent(Activity.java:2765)
                                                                        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:63)
                                                                        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:63)
                                                                        at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                                        at android.view.View.dispatchPointerEvent(View.java:9514)
                                                                        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
                                                                        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
                                                                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
                                                                        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
                                                                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
                                                                        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)
                                                                        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5857)
                                                                        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6025)
                                                                        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                        at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                                        at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
                                                                        at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5996)
                                                                        at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6048)
                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                    	at android.view.Choreographer.doCall
```
I copied the code from samples, so this is my code:

        final ListView listView = (ListView) findViewById(R.id.listview_predmety);
        final SwipeActionAdapter adapter = new SwipeActionAdapter(new Adapter(getApplicationContext()));
        adapter.setListView(listView);
        listView.setAdapter(new Adapter(getApplicationContext())); /*Adapter shown below*/

        adapter.addBackground(SwipeDirection.DIRECTION_NORMAL_LEFT, R.layout.rowbg_predmety_left)
                .addBackground(SwipeDirection.DIRECTION_NORMAL_RIGHT, R.layout.rowbg_predmety_right);
        adapter.setFarSwipeFraction(1);

        adapter.setSwipeActionListener(new SwipeActionAdapter.SwipeActionListener() {
            @Override
            public boolean hasActions(int position, SwipeDirection direction){
                if(direction.isLeft()) return true; // Change this to false to disable left swipes
                if(direction.isRight()) return true;
                return false;
            }

            @Override
            public boolean shouldDismiss(int position, SwipeDirection direction){
                // Only dismiss an item when swiping normal left
                return direction == SwipeDirection.DIRECTION_NORMAL_LEFT;
            }

            @Override
            public void onSwipe(int[] positionList, SwipeDirection[] directionList){
                for(int i=0;i<positionList.length;i++) {
                    SwipeDirection direction = directionList[i];
                    int position = positionList[i];
                    String dir = "";

                    if(direction.equals(SwipeDirection.DIRECTION_NORMAL_LEFT)){
                        dir = "Left";
                    } else if(direction.equals(SwipeDirection.DIRECTION_NORMAL_RIGHT)){
                        AlertDialog.Builder builder = new AlertDialog.Builder(PredmetyActivity.this);
                        builder.setTitle("Test Dialog").setMessage("You swiped right").create().show();
                        dir = "Right";
                    }
                    try {
                        String s = listView.getItemAtPosition(position).toString();
                        Log.d(TAG, "onSwipe: " + s);
                    } catch (NullPointerException e){
                        e.printStackTrace();
                    }
                    Toast.makeText(
                            getApplicationContext(),
                            dir + " swipe Action triggered on " + position,
                            Toast.LENGTH_SHORT
                    ).show();
                    adapter.notifyDataSetChanged();
                }
            }
        });

Adapter:

    private class Adapter extends BaseAdapter{

        private final Context context;
        private final LayoutInflater inflater;

        public Adapter(Context context) {
            this.context = context;;
            inflater = (LayoutInflater)context.
                    getSystemService(Context.LAYOUT_INFLATER_SERVICE);
        }

        @Override
        public int getCount() {
            Cursor cursor = GlobalValues.getDatabase(getApplicationContext()).getData("select count(*) from Subjects");
            cursor.moveToFirst();
            String count = cursor.getString(0);
            return Integer.parseInt(count);
        }

        @Override
        public Object getItem(int i) {
            return null;
        }

        @Override
        public long getItemId(int i) {
            return 0;
        }

        @Override
        public View getView(final int i, View view, ViewGroup viewGroup) {
            LinearLayout layout = (LinearLayout) inflater.inflate(R.layout.activity_listview_row, null);

            Cursor cursor = GlobalValues.getDatabase(context).getData("select Name, BasicImage, ProImage from Subjects");
            cursor.moveToPosition(i);

            ImageView image = (ImageView) layout.findViewById(R.id.image);
            if(cursor.getString(2) != null)
                image.setImageResource(getResources().getIdentifier(cursor.getString(2).replace(".png", ""), "drawable", context.getPackageName()));
            else image.setImageResource(android.R.color.transparent);

            TextView textView = (TextView) layout.findViewById(R.id.text);
            textView.setText(cursor.getString(0));
            return layout;
        }
    }`
Please someone help me

**Comment by robineki** [comment]
solved by myself. somehow -_-

**Comment by robineki** [comment]
I have new problem. If I scroll down i get render bug (it is in czech language if you dont understand) shown below
![device-2016-10-15-213733](https://cloud.githubusercontent.com/assets/22859297/19412901/fa37499e-931f-11e6-9ed2-35aa95024d51.png)
It must looks like this:
![device-2016-10-15-214157](https://cloud.githubusercontent.com/assets/22859297/19412915/4fe4d456-9320-11e6-96f6-22f1098728b2.png)
i dont know

**Comment by wdullaer** [comment]
That doesn't look like an issue with this adapter really.

I had a quick scan through your code and you are inflating a new layout every time `getView` is called. This is very inefficient; you're supposed to reuse the layouts you already created.

Judging by the render issues, it's most likely related: you are rendering the new content over the old one. My guess is that if you properly reuse the layouts, the issue will go away (and your memory/cpu usage will be massively improved)

**Comment by robineki** [comment]
So, how I clear the old one?

**Comment by robineki** [comment]
Yep, you're right. Fixed by replacing this:

`LinearLayout layout = (LinearLayout) inflater.inflate(R.layout.activity_listview_row, null);`
to this:

            LinearLayout layout;
            if(view == null)
                layout = (LinearLayout) inflater.inflate(R.layout.activity_listview_row, null);
            else layout = (LinearLayout) view;
